name: "EasterEggs"
version: 1.0.0
description: "An easy way to add nice looking eggs to your server!"
author: "DerDevHD"
api:
  - 3.0.0
main: eastereggs\EasterEggs

mcpe-protocols:
  - 407
  - 408

permissions:
  eastereggs.command:
    default: op